services:
#    soft_uni.example:
#        class: SoftUniBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    # First we define some basic services to make these utilities available in
    # the entire application
    slugger:
        class: SoftUniBundle\Service\Slugger

    softuni.product_repository:
        class: Doctrine\ORM\EntityRepository
        factory:   ["@doctrine.orm.entity_manager", getRepository]
        arguments: [SoftUniBundle\Entity\Product]

    softuni.product_manager:
        class: SoftUniBundle\Service\ProductManager
        arguments: ["@doctrine.orm.entity_manager", "@service_container", "@softuni.product_repository"]

    softuni.product_category_manager:
        class: SoftUniBundle\Service\ProductCategoryManager
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]

    softuni.notify_manager:
        class: SoftUniBundle\Service\NotifyManager
        arguments: ["@service_container"]